services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5490:5432'
    volumes:
      - ~/.docker-conf/postgres-db:/var/lib/postgresql/data
  app:
    image: 211125352081.dkr.ecr.ap-southeast-1.amazonaws.com/blueharvest-go:latest
    pull_policy: always
    restart: always
    depends_on:
      - db
    ports:
      - '8090:8080'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - RAJAONGKIR_API_KEY=${RAJAONGKIR_API_KEY}
      - KEY_GCS=${KEY_GCS}
      - XDT_CALLBACK_VERIFICATION=${XDT_CALLBACK_VERIFICATION}
      - XDT_SECRET_API_KEY=${XDT_SECRET_API_KEY}
      - OPEN_API_ASSISTANT_ID=${OPEN_API_ASSISTANT_ID}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - REDIS_URI=${REDIS_URI}