services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5490:5432'
    volumes:
      - ~/.docker-conf/postgres-db:/var/lib/postgresql/data
  app:
    image: irvansn/blueharvest-backend:latest
    pull_policy: always
    restart: always
    depends_on:
      - db
    ports:
      - '8090:8080'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}